const CONFIG = {
	API_MAX_LATENCY_MS: 2000,
	API_SUCCESS_THRESHOLD_MS: 1990,
	TABLE_DATA_LIMIT: 10,
	POST_LIMIT: 20,
	AUTOCOMPLETE_OPTIONS_LIMIT: 10,
	SORT_ORDER: {
		ASCENDING: 'asc',
		DESCENDING: 'desc',
		NONE: 'none',
	},
	THROTTLE_MS: 1000,
	API_THROTTLE_MS: 400,
};

export { CONFIG };
