const CONFIG = {
	API_MAX_LATENCY_MS: 1000,
	API_SUCCESS_THRESHOLD_MS: 990,
	TABLE_DATA_LIMIT: 10,
	POST_LIMIT: 20,
	SORT_ORDER: {
		ASCENDING: 'asc',
		DESCENDING: 'desc',
		NONE: 'none',
	},
};

export { CONFIG };
